BookstoreMvcProject/Models/Bookstore.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BookstoreMvcProject.Models
{
	public class Bookstore
	{
		public int Id { get; set; }

		[Required]
		[StringLength(80)]
		public string Name { get; set; }

		public List<Book> Books { get; set; }

		public Bookstore()
		{
			this.Books = new List<Book>();
		}

		public Bookstore(int id, string name)
		{
			this.Id = id;
			this.Name = name;
			this.Books = new List<Book>();
		}
	}
}

BookstoreMvcProject/Controllers/BookstoresController.cs
using System.Web.Mvc;
using BookstoreMvcProject.Models;
using BookstoreMvcProject.Interfaces;
using BookstoreMvcProject.Repository;

namespace BookstoreMvcProject.Controllers
{
	[RoutePrefix("Knjizara")]
    public class BookstoresController : Controller
    {
		private IBookRepo bookRepo = new BookRepo();
		private IBookstoreRepo bookstoreRepo = new BookstoreRepo();

		[Route("")]
		public ActionResult Index()
		{
			return View();
		}

		[Route("Napravi")]
		public ActionResult Add(Bookstore bookstore)
		{
			if (bookstore == null)
			{
				return View("Error");
			}

			if (ModelState.IsValid)
			{
				if (bookstoreRepo.Create(bookstore))
				{
					return RedirectToAction("List");
				}
			}
			return View("Error");
		}

		[Route("Izlistaj")]
		public ActionResult List()
		{
			var bookstores = bookstoreRepo.ReadAll();

			return View(bookstores);
		}

		[Route("Azuriraj/{id:int}")]
		public ActionResult Update(int id)
		{
			var bookstore = bookstoreRepo.ReadById(id);

			return View(bookstore);
		}

		[Route("Azuriraj")]
		[HttpPost]
		public ActionResult Update(Bookstore bookstore)
		{
			if (bookstore == null)
			{
				return View("Error");
			}

			if (ModelState.IsValid)
			{
				bookstoreRepo.Update(bookstore);

				return RedirectToAction("List");
			}
			return View("Error");
		}

		[Route("Pretrazi")]
		public ActionResult Search()
		{
			return View();
		}

		public ActionResult SearchResults(string searchQuery, int searchCategory)
		{
			if (searchQuery == null)
			{
				return View("Error");
			}

			var books = bookRepo.Search(searchQuery, searchCategory);

			if (books != null)
			{
				return View(books);
			}
			return View("Error");
		}

		[Route("Sortiraj")]
		public ActionResult Sort()
		{
			return View();
		}

		public ActionResult SortResults(int sortBy, int order)
		{
			var books = bookRepo.Sort(sortBy, order);

			if (books != null)
			{
				return View(books);
			}
			return View("Error");
		}

		[Route("Obrisi/{id:int}")]
		public ActionResult Delete(int id)
		{
			bookstoreRepo.Delete(id);

			return RedirectToAction("List");
		}
	}
}

BookstoreMvcProject/Views/Bookstores/Index.cshtml
@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Napravi", "Knjizara", FormMethod.Post))
{
	@Html.Label("Bookstore name", new { @for = "name" })
	@Html.TextBox("name", null, new { @type = "text", @class = "adding", @id = "name", @placeholder = "Naziv knjizare" })
	@Html.TextBox("submit", "Add bookstore", new { @type = "submit", @class = "adding" })
}

BookstoreMvcProject/Views/Bookstores/List.cshtml
@model IEnumerable<BookstoreMvcProject.Models.Bookstore>
@{
	ViewBag.Title = "List";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<table>
	<tr>
		<th>Id</th>
		<th>Name</th>
		<th></th>
		<th></th>
	</tr>
	@foreach (var bs in Model)
	{
		<tr>
			<td>@Html.DisplayFor(m => bs.Id)</td>
			<td>@Html.DisplayFor(m => bs.Name)</td>
			<td>@Html.ActionLink("Obrisi", "Obrisi", "Knjizara", new { Id = bs.Id }, null)</td>
			<td>@Html.ActionLink("Azuriraj", "Azuriraj", "Knjizara", new { Id = bs.Id }, null)</td>
		</tr>
	}
</table>

BookstoreMvcProject/Views/Bookstores/Search.cshtml
@{
	ViewBag.Title = "Search";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("SearchResults", "Bookstores", FormMethod.Get, new { @id = "searchOrSort", @class = "form-inline" }))
{
	@Html.TextBox("searchQuery", null, new { @type = "text", @placeholder = "Unesite kriterijum pretrage" })
	@Html.Label("search by", new { @for = "category" })
	<select id="category" , name="searchCategory">
		<option value="1">Po naslovu</option>
		<option value="2">Po zanru</option>
		<option value="3">Po poglavlju</option>
	</select>

	<button type="submit">Pretraga</button>
}

BookstoreMvcProject/Views/Bookstores/SearchResults.cshtml
@model IEnumerable<BookstoreMvcProject.Models.Book>
@{
	ViewBag.Title = "SearchResults";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<table>
	<tr>
		<th>I.Br.</th>
		<th>Naslov</th>
		<th>Cena</th>
	</tr>
	@foreach (var book in Model)
	{
		<tr>
			<td>@Html.DisplayFor(m => book.Id)</td>
			<td>@Html.DisplayFor(m => book.Title)</td>
			<td>@Html.DisplayFor(m => book.Price)</td>
		</tr>
	}
</table>

BookstoreMvcProject/Views/Bookstores/Sort.cshtml
@{
	ViewBag.Title = "Sort";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("SortResults", "Bookstores", FormMethod.Get, new { @id = "searchOrSort", @class = "form-inline" }))
{
	<select id="sortBy" name="sortBy">
		<option value="1">Naslov</option>
		<option value="2">Cena</option>
	</select>
	@Html.Label("", new { @for = "order" })
	<select id="order" name="order">
		<option value="1">Rastuce</option>
		<option value="2">Opadajuce</option>
	</select>
	<button type="submit">Sortiraj</button>
}

BookstoreMvcProject/Views/Bookstores/SortResults.cshtml
@model IEnumerable<BookstoreMvcProject.Models.Book>
@{
	ViewBag.Title = "SortResults";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<table>
	<tr>
		<th>I.Br.</th>
		<th>Naslov</th>
		<th>Cena</th>
	</tr>
	@foreach (var book in Model)
	{
		<tr>
			<td>@Html.DisplayFor(m => book.Id)</td>
			<td>@Html.DisplayFor(m => book.Title)</td>
			<td>@Html.DisplayFor(m => book.Price)</td>
		</tr>
	}
</table>

BookstoreMvcProject/Views/Bookstores/Update.cshtml
@model BookstoreMvcProject.Models.Bookstore
@{
	ViewBag.Title = "Update";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Azuriraj", "Knjizara", FormMethod.Post))
{
	<table>
		<tr>
			<th>Naziv</th>
			<td>
				@Html.Hidden("Bookstore.Id", Model.Id)
				@Html.TextBox("Bookstore.Name", Model.Name)
			</td>
		</tr>
		<tr colspan="2">
			<td>@Html.TextBox("submit", "Update bookstore", new { @type = "submit", @class = "adding" })</td>
		</tr>
	</table>
}